apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: pg-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 10Gi
  numberOfInstances: 2
  users:
    admin:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    test: admin  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "16"
