version: '3.8'

services:
  es-learn:
    container_name: 'es-learn'
    hostname: 'es-learn'
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      # - XPACK_MONITORING_ENABLED=true
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

  kibana-learn:
    container_name: 'kibana-learn'
    hostname: 'kibana-learn'
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - '5601:5601'
    environment:
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_HOSTS=http://es-learn:9200
